### ISSUE TITLE
Question: Does it work on node 10.12 or iojs?

### ISSUE THREAD

**Issue by 0x4139** [danielsen/node-pmta#4]
If not, do you accept pull requests?

**Comment by danielsen** [comment]
This was developed on node 10.24 and should work on 10.12. It's untested on iojs. Pull requests are accepted.

**Comment by kksohail** [comment]
is it necessary to use the PMTA submission api requires it being on the same server as PMTA itself. or we can class this from another server as well?

**Comment by danielsen** [comment]
This module needs to be built on a machine that has the PMTA API header files but once that is completed, it can submit messages to any machine running PMTA. Of course, the PMTA instances you're submitting to need to be configured to accept API submissions from the remote instance of this software.

**Comment by kksohail** [comment]
sorry to bother you again, I am very new in PMTA, I hope you will not mind my questions,
I have to just run this file to make a message submission (https://github.com/danielsen/node-pmta/blob/master/test/pmta_test.js) I have to install following before above operation, if I am wrong please correct me.

NodeJS v0.10+
npm - Usually packaged with NodeJS
pmta submission API.

**Comment by danielsen** [comment]
Correct. NodeJS, npm, and the PMTA submission API all need be installed before building / using this software.

**Comment by kksohail** [comment]
I am trying to pmta_test.js and I am getting this message 

ReferenceError: require is not defined

var pmta = require('../index.js');

can you please tell me what I am missing?

**Comment by kksohail** [comment]
sorry to bother you again and again, 

I run pmta_test.js from the terminal and got this message,

Error: Cannot find module './build/Release/pmta'

can you please guide me from where I can get this module?

**Comment by danielsen** [comment]
Make sure that you've run `npm build .` in the top-level directory after cloning the repository. That will build the required module.

**Comment by kksohail** [comment]
Hi,

I am able to run the script and got message "{ submitted: true }".

But I am not receiving email, I have provide correct host/port, sender and to email address, can you tell me what is still missing?

Thank you as always for your help

**Comment by danielsen** [comment]
Receiving `{submitted: true}` indicates that the message was accepted successfully by your Pmta installation. Check your Pmta accounting logs to track it down.

**Comment by kksohail** [comment]
thank you default VMTA was not define, this is got fixed.

I have more question, it possible to send multiple messages with different subject and message body through this script?

**Comment by danielsen** [comment]
Yes that's possible to a degree using the mail merge methods. The script does this already with the `[fname]` variable for replacing the first name. It can be extended to use other variables.

Say this is your recipients array:

    var recipients = [
      {
        "to" : "jane@domain.tld",
        "fname" : "jane",
        "subject" : "Order confirmation 12345"
      },
      {
        "to" : "john@domain.tld",
        "fname" : "john",
        "subject" : "Shipping confirmation 54321"
      }
    ]; 

When adding the recipients to the message, define all the variables that should be merged:

    for (var j=0; j < recipients.length; j++) {
      var rcpt = new pmta.Recipient(recipients[j].to);
      rcpt.defineVariable("*parts", "1");
      rcpt.defineVariable("to", recipients[j].to);
      rcpt.defineVariable("fname", recipients[j].fname);
      rcpt.defineVariable("subject", recipients[j].subject);
      msg.addRecipient(rcpt);
    }

Then anywhere `[subject]` appears in the message payload (header fields included), the appropriate subject string will be used for each recipient.

There may be some limits imposed by Pmta on how large a recipient variable can be so you may not be able to have a totally different message body for each recipient using this method but you should be able to personalize the message body to a high degree.

**Comment by kksohail** [comment]
Thank you for supporting me, I have one basic question, if include the pmta_test.js something like this exec("node /etc/pmta//node-pmta/test/pmta-html.js &", $output); in loop. will it cause any connection limit issue? Because in my case I will always have different subject / message body.

**Comment by danielsen** [comment]
I believe that the connection limit is defined at the `source-group` scope in the Pmta config so if you're hitting a limit it would be there. By default that directive is set to `unlimited` so I doubt that you're going to see any problems with that kind of loop. The Pmta support people would be a better resource for that question than me though. The obvious bottleneck here is that without using the mail-merge options you're forcing Pmta to write a spool file for each message. This is not going to be a problem at smaller scales but if you're planning to work with hundreds of thousands of messages you may see a slow down in submission as your CPU and HDDs become taxed. If you really can't use mail-merge, the most effective way to do this kind of submission would be to open a single connection, compose the messages as needed and submit them singly or in batches to the connection.

**Comment by kksohail** [comment]
I am sending messing though a loop one by one, is the connection will close automatically in the loop, or I have to place something like this, 
var cn = new pmta.Connection(pmta_host, pmta_port);
var res = cn.submit(msg);
cn.close();

?

**Comment by danielsen** [comment]
The Pmta API doesn't provide a close method so I chose not to implement my own. The connection, message, and recipient objects will all be cleaned up by V8 / Javascript garbage collection when they go out of scope so there's no need to close or delete them.

**Comment by kksohail** [comment]
its mean if I send millions of messages one by one it will not cause any harm?

**Comment by danielsen** [comment]
It's not likely to cause any problems, it's just not efficient and therefore likely won't scale particularly well. As noted previously, there are overhead costs associated with submitting single messages on single connections. You can do it, but there are going to be bottlenecks that slow submission some.

**Comment by kksohail** [comment]
some times my emails go into the junk/spam folder, is there any thing required to place in the header which I am missing?

**Comment by 0x4139** [comment]
What's the point of using the pmta submission API if they do the exact the same thing as if you were feeding using the SMTP API? I mean it looks like a headache instead of feeding directly to the smtp

**Comment by danielsen** [comment]
@0x4139 Primarily because it's a bit easier to use mail-merge via the API. Mail-merge is supported in SMTP submission but utilizing it would require creating a custom SMTP client that could send the Pmta SMTP verb extensions. In fact, that's what the submission API is: a SMTP client that integrates all the Pmta verb extensions. It's a question of where you want to do the work. I've written enough custom SMTP code to last me a while, at this point I'd rather just use the API.

**Comment by danielsen** [comment]
@kksohail Make sure that you're signing your emails with DKIM and that you've got SPF configured. See http://www.openspf.org/ and http://dkim.org/. Those are the primary authentication mechanisms that help mailbox providers identify your email.

Don't count on technical solutions to placement problems though. Message placement is driven by reputation and reputation is driven subscriber perception. In short, deliver a wanted message to a recipient who is expecting it. SpamHaus is a pretty good starting place for best practices: https://www.spamhaus.org/faq/section/Marketing%20FAQs
